- hosts: all
  sudo: true
  pre_tasks:
      - file: name="/etc/ssl" state=directory owner=www-data
      - copy: src=test/sandstorm.crt dest=/etc/ssl/ssl_certificate.crt
      - copy: src=test/sandstorm.key dest=/etc/ssl/ssl_certificate.key
      - copy: src=test/rootCA.pem dest=/etc/ssl/rootCA.pem
  vars_files:
      - test/vars.yml
  roles:
    - role: sandcastle
      sandstorm_dev_accounts: "yes"
      ssh_debug: true
      firewall_allowed_tcp_ports:
        - 22
        - 80
        - 443
      enable_mta: true
      ssl_certificate_path: /etc/ssl/ssl_certificate.crt
      ssl_certificate_key_path: /etc/ssl/ssl_certificate.key
      ssl_trusted_certificate_path: /etc/ssl/rootCA.pem
      backup_target: file:///tmp/backup
      backup_target_password: SUPERTRASH
      backup_enc_key_path: test/backup-encryption-private.key
      backup_sig_key_path: test/backup-signing-private.key
    - role: debops.cryptsetup
      sandstorm_ciphertext_block_device: '/dev/loop0'
